Test10/Controllers/OglasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test10.Data;
using Test10.Models;
using Test10.ViewModels;
using Microsoft.Extensions.Options;

namespace Test10.Controllers
{
    public class OglasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;
        

        public OglasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;          
        }

        // GET: Oglas
        public async Task<IActionResult> Index()
        {     
            var applicationDbContext = _context.Oglas.Include(o => o.Igrac).Include(o => o.TeniskiKlub);           
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Oglas
        public async Task<IActionResult> IgracOglasi() {

            if (User.IsInRole("Igrac"))
            {
                var appDbContext = _context.Oglas.Include(o => o.Igrac).Include(o => o.TeniskiKlub).Where(u => u.IgracId != _userManager.GetUserId(User)).OrderByDescending(o=>o.Datum);
                return View(await appDbContext.ToListAsync());
            }
            else
            {
                return View(nameof(Index));
            }
         
            
        }

        public async Task<IActionResult> SviOglasi(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var applicationContext = from t in _context.Oglas.Include(o => o.Igrac).Include(o => o.TeniskiKlub)
                                     select t;

            if (User.IsInRole("Igrac"))
            {
                var mojID = _userManager.GetUserId(User);
                if (!String.IsNullOrEmpty(searchString))
                {
                    applicationContext = applicationContext.Where(t => t.IgracId != mojID).Where(t => t.TeniskiKlub.Naziv.ToUpper().Contains(searchString.ToUpper())).OrderByDescending(t => t.Datum);
                    return View(await applicationContext.ToListAsync());
                }
                var appDbContext = _context.Oglas.Include(o => o.Igrac).Include(o => o.TeniskiKlub).Where(u => u.IgracId != _userManager.GetUserId(User)).OrderByDescending(o => o.Datum);
                return View(await appDbContext.ToListAsync());
            }
            else
            {
                return View(nameof(Index));
            }


        }

        // GET: Oglas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oglas = await _context.Oglas
                .Include(o => o.Igrac)
                .Include(o => o.TeniskiKlub)
                .SingleOrDefaultAsync(m => m.IdOglas == id);
            if (oglas == null)
            {
                return NotFound();
            }

            return View(oglas);
        }

        // GET: Oglas/Create
        public IActionResult Create()
        {
            // ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv");
            return View();
        }

        // POST: Oglas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdOglas,NazivOglas,Opis,TeniskiKlubId")] Oglas oglas)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                oglas.IgracId = user.Id;
                oglas.Datum = DateTime.Now;
                _context.Add(oglas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id", oglas.IgracId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", oglas.TeniskiKlubId);
            return View(oglas);
        }

        // GET: Oglas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oglas = await _context.Oglas.SingleOrDefaultAsync(m => m.IdOglas == id);
            if (oglas == null)
            {
                return NotFound();
            }
            ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id", oglas.IgracId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", oglas.TeniskiKlubId);
            return View(oglas);
        }

        // POST: Oglas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdOglas,NazivOglas,Opis,TeniskiKlubId")] Oglas oglas)
        {
            if (id != oglas.IdOglas)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    oglas.IgracId = user.Id;
                    oglas.Datum = DateTime.Now;
                    _context.Update(oglas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OglasExists(oglas.IdOglas))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //      var igraci = await _userManager.GetUsersInRoleAsync("Igrac");
            //   var korisnici = igraci.Select(u => new
            //   {
            //        Id = u.Id,
            //        ImePrezime = u.Ime + " " + u.Prezime
            //    }).Where(igraci.);
            ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id", oglas.IgracId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", oglas.TeniskiKlubId);
            return View(oglas);
        }

        // GET: Oglas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oglas = await _context.Oglas
                .Include(o => o.Igrac)
                .Include(o => o.TeniskiKlub)
                .SingleOrDefaultAsync(m => m.IdOglas == id);
            if (oglas == null)
            {
                return NotFound();
            }

            return View(oglas);
        }

        // POST: Oglas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var oglas = await _context.Oglas.SingleOrDefaultAsync(m => m.IdOglas == id);
            _context.Oglas.Remove(oglas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OglasExists(int id)
        {
            return _context.Oglas.Any(e => e.IdOglas == id);
        }

        public async Task<IActionResult> MojiOglasi()
        {
            var applicationDbContext = _context.Oglas.Include(o => o.Igrac).Include(o => o.TeniskiKlub).OrderByDescending(o => o.Datum);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Oglas/Create
        public IActionResult MojCreate()
        {
            // ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv");
            return View();
           
        }

        // POST: Oglas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MojCreate([Bind("IdOglas,NazivOglas,Opis,TeniskiKlubId")] Oglas oglas)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                oglas.IgracId = user.Id;
                oglas.Datum = DateTime.Now;
                _context.Add(oglas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MojiOglasi));
            }
            // ViewData["IgracId"] = new SelectList(_context.Users, "Id", "Id", oglas.IgracId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", oglas.TeniskiKlubId);
            //return View(oglas);
            return View();
        }

        // GET: Oglas/Edit/5
        public async Task<IActionResult> MojEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oglas = await _context.Oglas.SingleOrDefaultAsync(m => m.IdOglas == id);
            if (oglas == null)

Test10/Controllers/TeniskiKlubsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test10.Data;
using Test10.Models;

namespace Test10.Controllers
{
    public class TeniskiKlubsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public TeniskiKlubsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TeniskiKlubs
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var applicationContext = from t in _context.TeniskiKlub.Include(t => t.Upravitelj)
                                     select t;
            if (User.IsInRole("Upravitelj"))
            {
                var mojId = _userManager.GetUserId(User);
                if (!String.IsNullOrEmpty(searchString))
                {
                    applicationContext = _context.TeniskiKlub.Include(t => t.Upravitelj).Where(u => u.UpraviteljId == mojId).Where(t => t.Naziv.ToUpper().Contains(searchString.ToUpper()));
                    return View(await applicationContext.ToListAsync());
                }
            applicationContext = _context.TeniskiKlub.Include(t => t.Upravitelj).Where(u => u.UpraviteljId == mojId);
            return View(await applicationContext.ToListAsync());
            }
            else
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    applicationContext = applicationContext.Where(t => t.Naziv.ToUpper().Contains(searchString.ToUpper()));
                    return View(await applicationContext.ToListAsync());
                }
                var applicationDbContext = _context.TeniskiKlub.Include(t => t.Upravitelj);
                return View(await applicationDbContext.ToListAsync());
            }
            
        }

        // GET: TeniskiKlubs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teniskiKlub = await _context.TeniskiKlub
                .Include(t => t.Upravitelj)
                .SingleOrDefaultAsync(m => m.IdTeniskiKlub == id);
            if (teniskiKlub == null)
            {
                return NotFound();
            }

            return View(teniskiKlub);
        }

        // GET: TeniskiKlubs/Create
        public IActionResult Create()
        {
            ViewData["UpraviteljId"] = new SelectList(_context.Users, "Id", "Ime");
            return View();
        }

        // POST: TeniskiKlubs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTeniskiKlub,Naziv,Adresa,BrojTerena")] TeniskiKlub teniskiKlub)
        {
            if (ModelState.IsValid)
            {

                var user = await _userManager.GetUserAsync(User);
                teniskiKlub.UpraviteljId = user.Id;
                teniskiKlub.Upravitelj = user;
                _context.Add(teniskiKlub);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           // ViewData["UpraviteljId"] = new SelectList(_context.Users, "Id", "Id", teniskiKlub.UpraviteljId);
            return View(teniskiKlub);
        }

        // GET: TeniskiKlubs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teniskiKlub = await _context.TeniskiKlub.SingleOrDefaultAsync(m => m.IdTeniskiKlub == id);
            if (teniskiKlub == null)
            {
                return NotFound();
            }
            var upravitelji = await _userManager.GetUsersInRoleAsync("Upravitelj");
            var korisnici = upravitelji.Select(u => new
            {
                Id = u.Id,
                ImePrezime = u.Ime + " " + u.Prezime
            });
            ViewData["Upravitelj"] = new SelectList(korisnici, "Id", "ImePrezime", teniskiKlub.UpraviteljId);
            return View(teniskiKlub);
        }

        // POST: TeniskiKlubs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTeniskiKlub,Naziv,Adresa,BrojTerena,UpraviteljId")] TeniskiKlub teniskiKlub)
        {
            if (id != teniskiKlub.IdTeniskiKlub)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teniskiKlub);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeniskiKlubExists(teniskiKlub.IdTeniskiKlub))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var upravitelji = await _userManager.GetUsersInRoleAsync("Upravitelj");
            var korisnici = upravitelji.Select(u => new
            {
                Id = u.Id,
                ImePrezime = u.Ime + " " + u.Prezime
            });
            ViewData["Upravitelj"] = new SelectList(korisnici, "Id", "ImePrezime", teniskiKlub.UpraviteljId);
            return View(teniskiKlub);
        }

        // GET: TeniskiKlubs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teniskiKlub = await _context.TeniskiKlub
                .Include(t => t.Upravitelj)
                .SingleOrDefaultAsync(m => m.IdTeniskiKlub == id);
            if (teniskiKlub == null)
            {
                return NotFound();
            }

            return View(teniskiKlub);
        }

        // POST: TeniskiKlubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teniskiKlub = await _context.TeniskiKlub.SingleOrDefaultAsync(m => m.IdTeniskiKlub == id);
            _context.TeniskiKlub.Remove(teniskiKlub);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeniskiKlubExists(int id)
        {
            return _context.TeniskiKlub.Any(e => e.IdTeniskiKlub == id);
        }
    }
}

Test10/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Test10</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>

    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>

    @* JSZip for client side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@
    
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>

</head>

<body>

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">Test10</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"><a href="#" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>

</html>

Test10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZavrsniRad</title>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:#00004d;">
            <div class="container">               
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img class="nav navbar-nav navbar-left" src="~/images/ICFball4-512.png" width="33" height="40" style="padding-top:12px;padding-right:5px;" />
                    <a style="color:white;font-size:20px" asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"> Igraj tenis</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li><a style="color:white;font-size:18px" asp-area="" asp-controller="TeniskiKlubs" asp-action="Index">Klubovi</a></li>
                        <li><a style="color:white;font-size:18px" asp-area="" asp-controller="Terens" asp-action="Index">Tereni</a></li>
                        @if (User.IsInRole("Igrac"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i style="color:white;font-size:21px" class="far fa-envelope"></i><span class="caret"></span></a>
                                <!-- <button class="btn"><i class="far fa-envelope"></i></button>-->
                                <ul class="dropdown-menu" style="background-color:#b3b3ff;font-size:16px">
                                    <li><a asp-area="" asp-controller="Porukas" asp-action="PrimljenePoruke">Primljene poruke</a></li>
                                    <li><a asp-area="" asp-controller="Porukas" asp-action="PoslanePoruke">Poslane poruke</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a style="color:white;font-size:18px" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Oglasi<span class="caret"></span></a>
                                <!-- <button class="btn"><i class="far fa-envelope"></i></button>-->
                                <ul class="dropdown-menu" style="background-color:#b3b3ff;font-size:16px">
                                    <li><a asp-area="" asp-controller="Oglas" asp-action="SviOglasi">Oglasi</a></li>
                                    <li><a asp-area="" asp-controller="Oglas" asp-action="MojiOglasi">Moji oglasi</a></li>
                                    <li><a asp-area="" asp-controller="Oglas" asp-action="MojCreate"><i class="fas fa-plus"></i> Novi oglas</a></li>
                                </ul>
                            </li>
                        }

                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Teniski tereni</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    </body>
</html>