Test10/Models/Oglas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Test10.Models
{
    public partial class Oglas
    {

        public int IdOglas { get; set; }
        [Required(ErrorMessage = "Unesite naziv oglasa.")]
        [MaxLength(80, ErrorMessage = "Unesite manje od 80 znakova.")]
        public string NazivOglas { get; set; }
        [Required(ErrorMessage = "Unesite opis oglasa.")]
        [MaxLength(140, ErrorMessage = "Unesite manje od 140 znakova.")]
        public string Opis { get; set; }
        public DateTime Datum { get; set; }
        public string IgracId { get; set; }
        public int TeniskiKlubId { get; set; }

        public ApplicationUser Igrac { get; set; }
        public TeniskiKlub TeniskiKlub { get; set; }
    }
}

Test10/Controllers/PorukasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test10.Data;
using Test10.Models;
using Microsoft.AspNetCore.Identity;

namespace Test10.Controllers
{
    public class PorukasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public PorukasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Porukas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Poruka.Include(p => p.IgracPosiljatelj).Include(p => p.IgracPrimatelj);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> PrimljenePoruke()
        {
            var user = _userManager.GetUserId(User);
            var applicationDbContext = _context.Poruka.Include(p => p.IgracPosiljatelj).Include(p => p.IgracPrimatelj).Where(p=>p.IgracPrimateljId == user).OrderByDescending(e => e.Vrijeme);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> PoslanePoruke()
        {
            var user = _userManager.GetUserId(User);
            var applicationDbContext = _context.Poruka.Include(p => p.IgracPosiljatelj).Include(p => p.IgracPrimatelj).Where(p => p.IgracPosiljateljId == user).OrderByDescending(e=>e.Vrijeme);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Porukas/Edit/5
             public IActionResult Odgovor(string IdPosiljatelj)
             {
                ViewBag.IgracPrimateljId =  IdPosiljatelj;
                ViewBag.primateljIme = _userManager.Users.Where(u => u.Id == IdPosiljatelj).FirstOrDefault().Ime;
                ViewBag.primateljPrezime = _userManager.Users.Where(u => u.Id == IdPosiljatelj).FirstOrDefault().Prezime;
            /*   if (id == null)
               {
                   return NotFound();
               }

               var poruka = await _context.Poruka.SingleOrDefaultAsync(m => m.IdPoruka == id);
               if (poruka == null)
               {
                   return NotFound();
               } */
            //  ViewData["IgracPrimateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPosiljateljId);
            return View();
             }

             // POST: Porukas/Edit/5
             // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
             // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
             [HttpPost]
             [ValidateAntiForgeryToken]
             public async Task<IActionResult> Odgovor(string IdPosiljatelj, [Bind("IdPoruka,TekstPoruke,NaslovPoruke,Vrijeme")] Poruka poruka)
             {
                 if (ModelState.IsValid)
                 {
                     var user = await _userManager.GetUserAsync(User);             
                     poruka.IgracPosiljateljId = user.Id;
                     poruka.IgracPosiljatelj = user;
                     poruka.IgracPrimateljId = IdPosiljatelj;
                     poruka.Vrijeme = DateTime.Now;
                     poruka.IgracPrimatelj = _userManager.Users.Where(a => a.Id == IdPosiljatelj).FirstOrDefault();
                     _context.Add(poruka);
                     await _context.SaveChangesAsync();
                     return RedirectToAction(nameof(PoslanePoruke));
                 }

            //  ViewData["IgracPrimateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPrimateljId);
                  ViewBag.IgracPrimateljId = IdPosiljatelj;
                  return View(poruka);
             }
            
        // GET: Porukas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poruka = await _context.Poruka
                .Include(p => p.IgracPosiljatelj)
                .Include(p => p.IgracPrimatelj)
                .SingleOrDefaultAsync(m => m.IdPoruka == id);
            if (poruka == null)
            {
                return NotFound();
            }

            return View(poruka);
        }

        // GET: Porukas/Create
        public async Task<IActionResult> Create()
        {
            var igraci = await _userManager.GetUsersInRoleAsync("Igrac");
            var korisnici = igraci.Select(u => new
            {
                Id = u.Id,
                ImePrezime = u.Ime + " " + u.Prezime
            });
            ViewData["IgracPrimateljId"] = new SelectList(korisnici, "Id", "ImePrezime");
            ViewData["IgracPosiljateljId"] = new SelectList(_context.Users, "Id", "Ime");
           // ViewData["IgracPrimateljId"] = new SelectList(_context.Users, "Id", "Ime");
            return View();
        }

        // POST: Porukas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPoruka,IgracPrimateljId,NaslovPoruke,TekstPoruke")] Poruka poruka)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                poruka.Vrijeme = DateTime.Now;
                poruka.IgracPosiljateljId = user.Id;
                _context.Add(poruka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var igraci = await _userManager.GetUsersInRoleAsync("Igrac");
            var korisnici = igraci.Select(u => new
            {
                Id = u.Id,
                ImePrezime = u.Ime + " " + u.Prezime
            });
            ViewData["IgracPrimateljId"] = new SelectList(korisnici, "Id", "ImePrezime", poruka.IgracPrimateljId);
            return View(poruka);
        }

        // GET: Porukas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poruka = await _context.Poruka.SingleOrDefaultAsync(m => m.IdPoruka == id);
            if (poruka == null)
            {
                return NotFound();
            }
            ViewData["IgracPosiljateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPosiljateljId);
            ViewData["IgracPrimateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPrimateljId);
            return View(poruka);
        }

        // POST: Porukas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPoruka,TekstPoruke,NaslovPoruke,Vrijeme,IgracPosiljateljId,IgracPrimateljId")] Poruka poruka)
        {
            if (id != poruka.IdPoruka)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(poruka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PorukaExists(poruka.IdPoruka))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IgracPosiljateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPosiljateljId);
            ViewData["IgracPrimateljId"] = new SelectList(_context.Users, "Id", "Id", poruka.IgracPrimateljId);
            return View(poruka);
        }

        // GET: Porukas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poruka = await _context.Poruka
                .Include(p => p.IgracPosiljatelj)
                .Include(p => p.IgracPrimatelj)
                .SingleOrDefaultAsync(m => m.IdPoruka == id);
            if (poruka == null)
            {
                return NotFound();
            }

            return View(poruka);
        }

        // POST: Porukas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var poruka = await _context.Poruka.SingleOrDefaultAsync(m => m.IdPoruka == id);
            _context.Poruka.Remove(poruka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PorukaExists(int id)
        {
            return _context.Poruka.Any(e => e.IdPoruka == id);
        }
    }
}

Test10/Views/Oglas/Create.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "Create";
}

<h2>Stvori novi oglas</h2>

<h4>Oglas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NazivOglas" class="control-label">Naslov</label>
                <input asp-for="NazivOglas" class="form-control" />
                <span asp-validation-for="NazivOglas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <!-- <div class="form-group">
        <label asp-for="IgracId" class="control-label"></label>
        <select asp-for="IgracId" class ="form-control" asp-items="ViewBag.IgracId"></select>
    </div> -->
            <div class="form-group">
                <label asp-for="TeniskiKlubId" class="control-label">Teniski klub</label>
                <select asp-for="TeniskiKlubId" class="form-control" asp-items="ViewBag.TeniskiKlubId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Stvori" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Povratak na popis</a>
</div>

Test10/Views/Oglas/Delete.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "Delete";
}

<h2>Brisanje</h2>

<h3>Jeste li sigurni da želite obrisati ovaj oglas?</h3>
<div>
    <h4>Oglas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Naslov
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NazivOglas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt>
            Igrač
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Igrac.Ime)
            @Html.DisplayFor(model => model.Igrac.Prezime)
        </dd>
        <dt>
            Teniski klub
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TeniskiKlub.Naziv)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdOglas" />
        <input type="submit" value="Obriši" class="btn btn-default" /> |
        <a asp-action="Index">Povratak na listu</a>
    </form>
</div>

Test10/Views/Oglas/Details.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Oglas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Igrac)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Igrac.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TeniskiKlub)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TeniskiKlub.Naziv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdOglas">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Test10/Views/Oglas/Edit.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "Edit";
}

<h2>Uredi</h2>

<h4>Oglas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdOglas" />
            <div class="form-group">
                <label asp-for="NazivOglas" class="control-label">Naslov</label>
                <input asp-for="NazivOglas" class="form-control" />
                <span asp-validation-for="NazivOglas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <!--  <div class="form-group">
                <label asp-for="IgracId" class="control-label"></label>
                <select asp-for="IgracId" class="form-control" asp-items="ViewBag.IgracId"></select>
                <span asp-validation-for="IgracId" class="text-danger"></span>
            </div> -->
            <div class="form-group">
                <label asp-for="TeniskiKlubId" class="control-label">Teniski klub</label>
                <select asp-for="TeniskiKlubId" class="form-control" asp-items="ViewBag.TeniskiKlubId"></select>
                <span asp-validation-for="TeniskiKlubId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Povratak na popis</a>
</div>

Test10/Views/Oglas/IgracOglasi.cshtml
@model IEnumerable<Test10.Models.Oglas>
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "IgracOglasi";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }

    .pspor {
        background-color: #3399ff;
        color:white;
        font-size:13px;
        transition-duration:0.4s;
        
    }
        .pspor:hover {
            color: #3399ff;
            background-color: white;
        }


    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

</style>
<body>
    <h2 style="color:white"><b>Oglasi</b></h2>

    <table class="table" id="tableOglas" style="background-color:white;border-radius: 10px">
        <thead>
            <tr style="font-weight: 900;color: #ffffff;background:#cc5200;border-radius: 10px">
                <th>
                    Teniski klub
                </th>
                <th>
                    Datum i vrijeme
                </th>
                <th>
                    Naslov
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Opis)
                </th>
                <th>
                    Igrač
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TeniskiKlub.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Datum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NazivOglas)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Opis)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Igrac.Ime)
                        @Html.DisplayFor(modelItem => item.Igrac.Prezime)
                    </td>
                    <td>

                        @if (item.IgracId != UserManager.GetUserId(User))
                        {
                            <a class="btn pspor" asp-action="Odgovor" asp-controller="Porukas" asp-route-IdPosiljatelj="@item.IgracId"><i class="fas fa-edit" style="font-size:15px"></i> Pošalji poruku</a>
                        }


                        <!--<a asp-action="Details" asp-route-id="@item.IdOglas">Details</a>-->

                    </td>
                </tr>
            }
        </tbody>
    </table>

</body>

Test10/Views/Oglas/Index.cshtml
@model IEnumerable<Test10.Models.Oglas>
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Index";
}
@if (User.IsInRole("Igrac"))
{

    <h2 style="color:white"><b>Oglasi</b></h2>

    
    <table class="table" id="tableOglas">
        <thead>
            <tr>
                <th>
                    Teniski klub
                </th>
                <th>
                    Datum i vrijeme
                </th>
                <th>
                    Naslov
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Opis)
                </th>
                <th>
                    Igrač
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TeniskiKlub.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NazivOglas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Igrac.Ime)
                    @Html.DisplayFor(modelItem => item.Igrac.Prezime)
                </td>
                <td>
                    @if (item.IgracId == UserManager.GetUserId(User))
                    {
                        <a asp-action="Edit" asp-route-id="@item.IdOglas">Uredi</a>
                        <a asp-action="Delete" asp-route-id="@item.IdOglas">Obriši</a>
                    }
                    @if (item.IgracId != UserManager.GetUserId(User))
                    {
                        <a asp-action="Odgovor" asp-controller="Porukas" asp-route-IdPosiljatelj="@item.IgracId">Pošalji poruku</a>
                    }
                        

                    <!--<a asp-action="Details" asp-route-id="@item.IdOglas">Details</a>-->

                </td>
            </tr>
            }
        </tbody>
    </table>
}

@section scripts{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tableOglas').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        });
    </script>
}

Test10/Views/Oglas/MojCreate.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "MojCreate";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }
</style>
<h2 style="color:white">Stvori novi oglas</h2>
<hr />
<div class="row">
    <div class="col-md-4" style="height:auto;padding-bottom:10px;padding-top:10px;background-color:#d9d9d9;border-radius: 15px;">
        <form asp-action="MojCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NazivOglas" class="control-label">Naslov</label>
                <input asp-for="NazivOglas" class="form-control" />
                <span asp-validation-for="NazivOglas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label">Oglas</label>
                <textarea asp-for="Opis" class="form-control"></textarea>
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <!-- <div class="form-group">
                <label asp-for="IgracId" class="control-label"></label>
                <select asp-for="IgracId" class ="form-control" asp-items="ViewBag.IgracId"></select>
            </div> -->
            <div class="form-group">
                <label asp-for="TeniskiKlubId" class="control-label">Teniski klub</label>
                <select asp-for="TeniskiKlubId" class="form-control" asp-items="ViewBag.TeniskiKlubId"></select>
            </div>
            <div class="form-group" align="center">
                <input type="submit" value="Stvori" class="btn btn-success" /> |
                <a class="btn btn-default" asp-action="MojiOglasi">Povratak na popis</a>

            </div>
        </form>
    </div>
</div>

Test10/Views/Oglas/MojDelete.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "MojDelete";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }
</style>

<h2 style="color:white"><b>Brisanje</b></h2>

<h3 style="color:white">Jeste li sigurni da želite obrisati ovaj oglas?</h3>
<div style="height:160px;width:400px ;background-color:#d9d9d9;border-radius: 15px">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Naslov
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NazivOglas)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt>
            Teniski klub
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TeniskiKlub.Naziv)
        </dd>
    </dl>
    <div align="center">
        <form asp-action="MojDelete">
            <input type="hidden" asp-for="IdOglas" />
            <input type="submit" value="Obriši" class="btn btn-danger" /> |
            <a class="btn btn-default" asp-action="MojiOglasi">Povratak na listu</a>
        </form>
        </div>
    </div>

Test10/Views/Oglas/MojEdit.cshtml
@model Test10.Models.Oglas

@{
    ViewData["Title"] = "MojEdit";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }

    .povratak {
        background-color: white;
    }
</style>


<h2 style="color:white"><b>Uredi</b></h2>

<div class="row">
    <div class="col-md-4" style="height:auto;padding-bottom:10px;padding-top:10px;background-color:#d9d9d9;border-radius: 15px;">
        <form asp-action="MojEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdOglas" />
            <div class="form-group">
                <label asp-for="NazivOglas" class="control-label">Naslov</label>
                <input asp-for="NazivOglas" class="form-control" />
                <span asp-validation-for="NazivOglas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <!--  <div class="form-group">
                <label asp-for="IgracId" class="control-label"></label>
                <select asp-for="IgracId" class="form-control" asp-items="ViewBag.IgracId"></select>
                <span asp-validation-for="IgracId" class="text-danger"></span>
            </div> -->
            <div class="form-group">
                <label asp-for="TeniskiKlubId" class="control-label">Teniski klub</label>
                <select asp-for="TeniskiKlubId" class="form-control" asp-items="ViewBag.TeniskiKlubId"></select>
                <span asp-validation-for="TeniskiKlubId" class="text-danger"></span>
            </div>
            <div class="form-group" align="center">
                <input type="submit" value="Spremi" class="btn btn-success" /> |
                <a class="btn btn-default" asp-action="MojiOglasi">Povratak na popis</a>
            </div>
        </form>
    </div>
</div>

Test10/Views/Oglas/SviOglasi.cshtml
@model IEnumerable<Test10.Models.Oglas>
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "SviOglasi";
}

<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: contain;
    }

    .card {
        background-color: #fff;
        border: 1px solid transparent;
        border-radius: 6px;
        width: 60%;
    }

    .card-header {
        border-radius: 6px 6px 0 0;
        padding: 5px;
        font-size: 15px;
    }

    .card .card-footer {
        border-radius: 0 0 6px 6px;
        padding: 5px;
    }

    .card .card-tijelo .lead {
        text-align: center;
    }

    .card-default {
        border-color: #ddd;
        background-color: #fff;
        margin-bottom: 10px;
    }

        .card-default > .card-header,
        .card-default > .card-footer {
            color: #333;
            background-color: #ddd;
        }


    .pspor {
        background-color: #3399ff;
        color: white;
        font-size: 13px;
        transition-duration: 0.4s;
    }

        .pspor:hover {
            color: #3399ff;
            background-color: white;
        }
</style>

<body>
    <h2 style="color:white" align="center"><b>Oglasi</b></h2>
    <hr />
    <form asp-action="SviOglasi" method="get">
        <div class="form-actions no-color" align="center">
            <p>
                <b><font size="4" style="color:white"> Pronađi klub:</font></b> <input type="text" style="border-radius: 5px" name="searchString" value="@ViewData["CurrentFilter"]" />
                <button type="submit" value="Search" class="btn btn-default"><i class="fas fa-search" style='font-size:15px'></i></button> |
                <a asp-action="SviOglasi" class="btn btn-default">Pregledaj sve </a>
            </p>
        </div>
    </form>

    @foreach (var item in Model)
    {
        <div align="center">
            <div class="card card-default">
                <div class="card-header" align="left">
                    <b>
                        @Html.DisplayFor(modelItem => item.Igrac.Ime)
                        @Html.DisplayFor(modelItem => item.Igrac.Prezime) :
                    </b> @Html.DisplayFor(modelItem => item.TeniskiKlub.Naziv)
                </div>
                <div class="card-tijelo">

                    <p class="lead">@Html.DisplayFor(modelItem => item.NazivOglas)</p>
                    <p style="font-size:18px;">@Html.DisplayFor(modelItem => item.Opis)</p>

                </div>
                <div class="card-footer" align="center">
                    Objavljeno:  @Html.DisplayFor(modelItem => item.Datum) |
                    @if (item.IgracId != UserManager.GetUserId(User))
                    {
                        <a class="btn pspor" asp-action="Odgovor" asp-controller="Porukas" asp-route-IdPosiljatelj="@item.IgracId"><i class="fas fa-edit" style="font-size:15px"></i>   Pošalji poruku</a>
                    }
                </div>
            </div>
        </div>
    }

</body>