Test10/Models/TeniskiKlub.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Test10.Models
{
    public partial class TeniskiKlub
    {
        public TeniskiKlub()
        {
            Oglas = new HashSet<Oglas>();
            Teren = new HashSet<Teren>();           
        }

        public int IdTeniskiKlub { get; set; }
        [Required(ErrorMessage = "Unesite naziv teniskog kluba.")]
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public int BrojTerena { get; set; }
        public string UpraviteljId { get; set; }
       
        public ApplicationUser Upravitelj { get; set; }
        public ICollection<Oglas> Oglas { get; set; }
        public ICollection<Teren> Teren { get; set; }
        
    }
}

Test10/Controllers/SchedulerDataController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Test10.Data;

namespace Test10.Models.Controllers
{
    [Route("api/[controller]/[action]")]
    public class SchedulerDataController : Controller
    {
        private ApplicationDbContext _context;

        public SchedulerDataController(ApplicationDbContext context) {
            this._context = context;
        }

        [HttpGet]
        public IActionResult Get(DataSourceLoadOptions loadOptions) {
            // var tereni = _context.Teren.Where(i => i.TeniskiKlubId == id).Select(i =>i.IdTeren).ToList();
            //  var rezervacija = _context.Rezervacija.Where(i=>tereni.Contains(i.TerenId)).Select(i => new {
            var rezervacija = _context.Rezervacija.Select(i => new {
                i.IdRezervacija,
                i.DatumVrijeme,
                i.Kraj,
                i.TerenId,
                i.UpraviteljId,
                i.IgracId
            });
            return Json(DataSourceLoader.Load(rezervacija, loadOptions));
        }

        [HttpPost]
        public IActionResult Post(string values) {
            var model = new Rezervacija();
            var _values = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, _values);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            var result = _context.Rezervacija.Add(model);
            _context.SaveChanges();

            return Json(result.Entity.IdRezervacija);
        }

        [HttpPut]
        public IActionResult Put(int key, string values) {
            var model = _context.Rezervacija.FirstOrDefault(item => item.IdRezervacija == key);
            if(model == null)
                return StatusCode(409, "Rezervacija not found");

            var _values = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, _values);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            _context.SaveChanges();
            return Ok();
        }

        [HttpDelete]
        public void Delete(int key) {
            var model = _context.Rezervacija.FirstOrDefault(item => item.IdRezervacija == key);

            _context.Rezervacija.Remove(model);
            _context.SaveChanges();
        }


        [HttpGet]
        public IActionResult TerenLookup(DataSourceLoadOptions loadOptions) {
            var lookup = from i in _context.Teren
                         orderby i.NazivTerena
                         select new {
                             Value = i.IdTeren,
                             Text = i.NazivTerena
                         };
            return Json(DataSourceLoader.Load(lookup, loadOptions));
        }

        private void PopulateModel(Rezervacija model, IDictionary values) {
            string ID_REZERVACIJA = nameof(Rezervacija.IdRezervacija);
            string DATUM_VRIJEME = nameof(Rezervacija.DatumVrijeme);
            string KRAJ = nameof(Rezervacija.Kraj);
            string TEREN_ID = nameof(Rezervacija.TerenId);
            string UPRAVITELJ_ID = nameof(Rezervacija.UpraviteljId);
            string IGRAC_ID = nameof(Rezervacija.IgracId);

            if(values.Contains(ID_REZERVACIJA)) {
                model.IdRezervacija = Convert.ToInt32(values[ID_REZERVACIJA]);
            }

            if(values.Contains(DATUM_VRIJEME)) {
                model.DatumVrijeme = Convert.ToDateTime(values[DATUM_VRIJEME]);
            }

            if(values.Contains(KRAJ)) {
                model.Kraj = Convert.ToDateTime(values[KRAJ]);
            }

            if(values.Contains(TEREN_ID)) {
                model.TerenId = Convert.ToInt32(values[TEREN_ID]);
            }

            if(values.Contains(UPRAVITELJ_ID)) {
                model.UpraviteljId = Convert.ToString(values[UPRAVITELJ_ID]);
            }

            if(values.Contains(IGRAC_ID)) {
                model.IgracId = Convert.ToString(values[IGRAC_ID]);
            }
        }

        private string GetFullErrorMessage(ModelStateDictionary modelState) {
            var messages = new List<string>();

            foreach(var entry in modelState) {
                foreach(var error in entry.Value.Errors)
                    messages.Add(error.ErrorMessage);
            }

            return String.Join(" ", messages);
        }
    }
}

Test10/Controllers/TerensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test10.Data;
using Test10.Models;

namespace Test10.Controllers
{
    public class TerensController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public TerensController(ApplicationDbContext context, UserManager<ApplicationUser>userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Terens
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            var applicationContext = from t in _context.Teren.Include(t => t.Podloga).Include(t => t.TeniskiKlub)
                         select t;
           /*if (!String.IsNullOrEmpty(searchString))
            {
                applicationContext = applicationContext.Where(t => t.TeniskiKlub.Naziv.Contains(searchString));
                return View(await applicationContext.ToListAsync());//Naziv.Contains(searchString));
            }*/
            if (User.IsInRole("Upravitelj"))
            {
                var mojID = _userManager.GetUserId(User);

                if (!String.IsNullOrEmpty(searchString))
                {
                    applicationContext = applicationContext.Where(u => u.TeniskiKlub.UpraviteljId == mojID).Where(t => t.TeniskiKlub.Naziv.ToUpper().Contains(searchString.ToUpper()));
                    return View(await applicationContext.ToListAsync());//Naziv.Contains(searchString));
                }
                applicationContext = _context.Teren.Include(t => t.Podloga).Include(t => t.TeniskiKlub).Where(u => u.TeniskiKlub.UpraviteljId == mojID);
                return View(await applicationContext.ToListAsync());
            }
            else
           {
                if (!String.IsNullOrEmpty(searchString))
                {
                    applicationContext = applicationContext.Where(t => t.TeniskiKlub.Naziv.ToUpper().Contains(searchString.ToUpper()));
                    return View(await applicationContext.ToListAsync());//Naziv.Contains(searchString));
                }
                var applicationDbContext = _context.Teren.Include(t => t.Podloga).Include(t => t.TeniskiKlub);
                return View(await applicationDbContext.ToListAsync());
           }
           
        }
        public async Task<IActionResult> IndexKluba(int id)
        {
            var applicationDbContext = _context.Teren.Include(t => t.Podloga).Include(t => t.TeniskiKlub).Where(u=>u.TeniskiKlubId==id);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: Terens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teren = await _context.Teren
                .Include(t => t.Podloga)
                .Include(t => t.TeniskiKlub)
                .SingleOrDefaultAsync(m => m.IdTeren == id);
            if (teren == null)
            {
                return NotFound();
            }

            return View(teren);
        }

        // GET: Terens/Create
        public IActionResult Create()
        {
            var mojId = _userManager.GetUserId(User);
            ViewData["PodlogaId"] = new SelectList(_context.Podloga, "IdPodloga", "NazivPodloga");
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub.Include(t => t.Upravitelj).Where(u => u.UpraviteljId == mojId), "IdTeniskiKlub", "Naziv");
            return View();
        }

        // POST: Terens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTeren,NazivTerena,PodlogaId,Prostor,TeniskiKlubId")] Teren teren)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teren);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var mojId = _userManager.GetUserId(User);
           // var klubovi = _context.TeniskiKlub.Include(t => t.Upravitelj).Where(u => u.UpraviteljId == mojId);
            ViewData["PodlogaId"] = new SelectList(_context.Podloga, "IdPodloga", "NazivPodloga", teren.PodlogaId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub.Include(t => t.Upravitelj).Where(u => u.UpraviteljId == mojId), "IdTeniskiKlub", "Naziv", teren.TeniskiKlubId);
            return View(teren);
        }

        // GET: Terens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teren = await _context.Teren.SingleOrDefaultAsync(m => m.IdTeren == id);
            if (teren == null)
            {
                return NotFound();
            }
            ViewData["PodlogaId"] = new SelectList(_context.Podloga, "IdPodloga", "NazivPodloga", teren.PodlogaId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", teren.TeniskiKlubId);
            return View(teren);
        }

        // POST: Terens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTeren,PodlogaId,Prostor,TeniskiKlubId")] Teren teren)
        {
            if (id != teren.IdTeren)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teren);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TerenExists(teren.IdTeren))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PodlogaId"] = new SelectList(_context.Podloga, "IdPodloga", "IdPodloga", teren.PodlogaId);
            ViewData["TeniskiKlubId"] = new SelectList(_context.TeniskiKlub, "IdTeniskiKlub", "Naziv", teren.TeniskiKlubId);
            return View(teren);
        }

        // GET: Terens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teren = await _context.Teren
                .Include(t => t.Podloga)
                .Include(t => t.TeniskiKlub)
                .SingleOrDefaultAsync(m => m.IdTeren == id);
            if (teren == null)
            {
                return NotFound();
            }

            return View(teren);
        }

        // POST: Terens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teren = await _context.Teren.SingleOrDefaultAsync(m => m.IdTeren == id);
            _context.Teren.Remove(teren);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TerenExists(int id)
        {
            return _context.Teren.Any(e => e.IdTeren == id);
        }
    }
}

Test10/Views/TeniskiKlubs/Create.cshtml
@model Test10.Models.TeniskiKlub

@{
    ViewData["Title"] = "Create";
}

<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }
    </style>

<body>

    <h2 style="color:white"><b>Stvori novi klub</b></h2>    
    <hr />
    <div class="row justify-content-center">
        <div class="col-md-4" style="height:auto;padding-bottom:10px;padding-top:10px;background-color:#d9d9d9;border-radius: 15px;">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Naziv" class="control-label"></label>
                    <input asp-for="Naziv" class="form-control" />
                    <span asp-validation-for="Naziv" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Adresa" class="control-label"></label>
                    <input asp-for="Adresa" class="form-control" />
                    <span asp-validation-for="Adresa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BrojTerena" class="control-label">Broj terena</label>
                    <input asp-for="BrojTerena" class="form-control" />
                    <span asp-validation-for="BrojTerena" class="text-danger"></span>
                </div>
                <!-- <div class="form-group">
                    <label asp-for="UpraviteljId" class="control-label"></label>
            <select asp-for="UpraviteljId" class="form-control" asp-items="ViewBag.UpraviteljId"></select>
        </div>-->
                <div class="form-group" align="center">
                    <input type="submit" value="Stvori" class="btn btn-success" /> |
                    <a class="btn btn-default" asp-action="Index">Povratak na popis</a>
                </div>
            </form>
           
        </div>
    </div>
    <!--
        <div>
            <a asp-action="Index">Povratak na popis</a>
        </div>
        -->

</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Test10/Views/TeniskiKlubs/Delete.cshtml
@model Test10.Models.TeniskiKlub

@{
    ViewData["Title"] = "Delete";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }
</style>
<body>
    <h2 style="color:white"><b>Brisanje</b></h2>
    <h3 style="color:white"><b>Jeste li sigurni da želite obrisati ovaj klub?</b></h3>
    <div style="height:200px;width:400px ;background-color:#d9d9d9;border-radius: 15px">
        <hr />
        <dl class="dl-horizontal" style="height:100px;width:400px ;background-color:#d9d9d9;border-radius: 15px">
            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>
            <dt>
                Broj terena
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BrojTerena)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Upravitelj)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Upravitelj.Ime)
                @Html.DisplayFor(model => model.Upravitelj.Prezime)
            </dd>
        </dl>       
        <div align="center">
            <form asp-action="Delete">
                <input type="hidden" asp-for="IdTeniskiKlub" />
                <input type="submit" value="Obriši" class="btn btn-danger" /> |
                <a class="btn btn-default" asp-action="Index">Povratak na popis</a>
            </form>
        </div>
    </div>

</body>

Test10/Views/TeniskiKlubs/Details.cshtml
@model Test10.Models.TeniskiKlub
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Details";
}
<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }
    .uredi {
        background-color: #ffcc00;
        color: white;
    }
        .uredi:hover {
            background-color: white;
            color: #ffcc00;
        }

</style>
<body>
    <h2 style="color:white"><b>Detalji</b></h2>

    <div style="height:180px;width:400px ;background-color:#d9d9d9;border-radius: 15px">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>
            <dt>
                Broj terena
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BrojTerena)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Upravitelj)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Upravitelj.Ime)
                @Html.DisplayFor(model => model.Upravitelj.Prezime)
            </dd>
        </dl>
        <div align="center">
            @if (User.IsInRole("Upravitelj") && Model.UpraviteljId == UserManager.GetUserId(User))
            {
                <a class="btn uredi" asp-action="Edit" asp-route-id="@Model.IdTeniskiKlub"><i class="far fa-edit" style='font-size:13px'></i> Uredi</a>
            }

            <a class="btn btn-default" asp-action="Index">Povratak na popis</a>
        </div>
    </div>
    


</body>

Test10/Views/TeniskiKlubs/Edit.cshtml
@model Test10.Models.TeniskiKlub

@{
    ViewData["Title"] = "Edit";
}

<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }

    .povratak {
        background-color: white;
    }
    </style>

<body>

    <h2 style="color:white"><b>Uredi</b></h2>
    <hr />
    <div class="row">
        <div class="col-md-4" style="height:auto;padding-bottom:10px;padding-top:10px;background-color:#d9d9d9;border-radius: 15px;">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="IdTeniskiKlub" />
                <div class="form-group">
                    <label asp-for="Naziv" class="control-label"></label>
                    <input asp-for="Naziv" class="form-control" />
                    <span asp-validation-for="Naziv" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Adresa" class="control-label"></label>
                    <input asp-for="Adresa" class="form-control" />
                    <span asp-validation-for="Adresa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BrojTerena" class="control-label">Broj terena</label>
                    <input asp-for="BrojTerena" class="form-control" />
                    <span asp-validation-for="BrojTerena" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpraviteljId" class="control-label">Upravitelj</label>
                    <select asp-for="UpraviteljId" class="form-control" asp-items="ViewBag.Upravitelj"></select>
                    <span asp-validation-for="UpraviteljId" class="text-danger"></span>
                </div>
                <div class="form-group" align="center">
                    <input type="submit" value="Spremi" class="btn btn-success" /> |
                    <a class="btn povratak" asp-action="Index">Povratak na popis</a>
                </div>
            </form>
          <!--  <div align="center">
                <a asp-action="Index">Povratak na popis</a>
            </div> -->
        </div>
    </div>
</body>
   

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Test10/Views/TeniskiKlubs/Index.cshtml
@model IEnumerable<Test10.Models.TeniskiKlub>
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-image: url(/images/ball-court-design-209977123.jpg);
        background-size: cover;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .gumb {
        background-color: #4CAF50;
        color: white;
        transition-duration: 0.4s;
    }

        .gumb:hover {
            background-color: white;
            color: #4CAF50;
        }

    .gumbi {
        color: white;
        transition-duration: 0.4s;
        font-size:7px;
    }

        .gumbi:hover {
            background-color: white;
        }

    .brisanje {
        background-color: #e60000;
    }

        .brisanje:hover {
            color: #e60000;
        }

    .uredi {
        background-color: #ffcc00;
    }

        .uredi:hover {
            color: #ffcc00;
        }

    .detalj {
        background-color: #0000ff;
    }

        .detalj:hover {
            color: #0000ff;
        }
</style>

<body>
    <h2 style="color:white"><b>Teniski klubovi</b></h2>

    <p>
        @if (User.IsInRole("Upravitelj"))
        {
            <a asp-action="Create" class="btn gumb"><i class="fas fa-plus" style='font-size:15px'> Stvori novi klub</i></a>
        }
    </p>

    <!-- <form asp-action="Index" method="get" style="background-color:#d9d9d9;border-radius: 5px">
          <div class="form-actions no-color">
              <p>
                  Pronađi klub: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
                  <input type="submit" value="Search" class="btn btn-default" /> |
                  <a asp-action="Index"> Pregledaj sve </a>
              </p>
          </div>
      </form>
        -->

    <table class="table" style="background-color:white;border-radius: 10px">
        <thead>
            <tr style="font-weight: 900;color: #ffffff;background:#cc5200;border-radius: 10px">
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Adresa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BrojTerena)
                </th>
                <!--   <th>
                       @Html.DisplayNameFor(model => model.Upravitelj)
                   </th> -->              
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="Terens" asp-action="IndexKluba" asp-route-id="@item.IdTeniskiKlub">@Html.DisplayFor(modelItem => item.Naziv)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adresa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BrojTerena)
                    </td>
                    <!--
                            <td>
                                @Html.DisplayFor(modelItem => item.Upravitelj.Ime)
                                @Html.DisplayFor(modelItem => item.Upravitelj.Prezime)
                            </td>
                    -->
                    <td>
                        @if (User.IsInRole("Upravitelj") && item.UpraviteljId == UserManager.GetUserId(User))
                        {
                            <a class="btn gumb uredi" asp-action="Edit" asp-route-id="@item.IdTeniskiKlub"><i class="far fa-edit" style='font-size:13px'></i></a>
                            <!--a class="btn gumb brisanje" asp-action="Delete" asp-route-id="@item.IdTeniskiKlub"><i class="far fa-trash-alt" style='font-size:13px'></i>  </a> -->
                        }

                        <a class="btn gumb detalj" asp-action="Details" asp-route-id="@item.IdTeniskiKlub"><i class="fas fa-ellipsis-h" style='font-size:13px'></i></a>
                        <a class="btn" asp-controller="SchedulerData" asp-action="Get" asp-route-id="@item.IdTeniskiKlub">Rezerviraj teren</a>
                </tr>
            }
        </tbody>
    </table>
</body>